# MoveIt uses this configuration for controller management
#trajectory_execution:
#  execution_duration_monitoring: 100
#  allowed_execution_duration_scaling: 100
#  allowed_goal_duration_margin: 0.5
#  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - tmr_arm_controller
  #wait_for_execution: true

  tmr_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    #execution_duration_monitoring: false
    #allowed_execution_duration_scaling: 10
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
